### ISSUE TITLE
Improving Text

### ISSUE THREAD

**Issue by aliaquintero** [ShrutiMishra-2002/hacktoberfest22_transopedia#12]
I would like to improve the grammar, punctuation, spelling, and capitalization in all of the sections in index.html. This would be a low/no code alteration. This includes the navigation, hero, about, services, etc.

**Comment by ShrutiMishra-2002** [comment]
Please make a valid issue ! @aliaquintero

**Comment by aliaquintero** [comment]
@ShrutiMishra-2002 I don't see how this isn't a valid issue, a lot of the writing style is inconsistent throughout the page and improving the structure of all the writing in that index.html would improve readability, accessibility, etc. The page overall is difficult to read.
