### ISSUE TITLE
Make the feedback button active

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [ShrutiMishra-2002/hacktoberfest22_transopedia#15]
-Make the feedback button active using a third-party API or backend services
-Visit the website for more details:- https://shrutimishra-2002.github.io/Transopedia-web
![03 10 2022_00 22 27_REC](https://user-images.githubusercontent.com/87663868/193471152-8873aff7-61e4-47db-92da-4215fed4d0ed.png)
site/

**Comment by palashb01** [comment]
Hey @ShrutiMishra-2002, I think I can do this.
Implementations:
-> Create a Feedback Page that will be Opened by this disabled Button
-> Use the Form Submit API to send the automated mail with captcha to the desired mail
-> Independent Page for Feedback with Good Styling

Objectives:
-> Feedback Page
-> FormSubmit API

**Comment by palashb01** [comment]
@ShrutiMishra-2002 @mdnazisharman2803  Kindly Provide a Mail to be used for the formsubmit API
