### ISSUE TITLE
Footer changes

### ISSUE THREAD

**Issue by pranavsuriya-sr** [ShrutiMishra-2002/hacktoberfest22_transopedia#31]
Adding the social media icons and the navbar links to the footer can make it look elegant.

**Comment by riyatyag-6** [comment]
Font color of the footer can also be changed to make it more readable because the background and font color looks similar.
Kindly assign this issue to me.

**Comment by ShrutiMishra-2002** [comment]
Please share the screenshot @riyatyag-6

**Comment by riyatyag-6** [comment]
![Screenshot_20221009-010522~2.png](https://user-images.githubusercontent.com/75671046/194724580-8191dff5-3fae-4970-8507-ae1334e8aed2.png)

**Comment by riyatyag-6** [comment]
Even we can change the gradient color to make it more visible.

**Comment by pranavsuriya-sr** [comment]
As I created the issue it would be great if you could assign it to me please.

**Comment by ShrutiMishra-2002** [comment]
not up to the mark @riyatyag-6 so closing it
