### ISSUE TITLE
Improving the services Provided Section

### ISSUE THREAD

**Issue by theanimator20** [ShrutiMishra-2002/hacktoberfest22_transopedia#40]
Hey @ShrutiMishra-2002  , i would like to improve the **Services provided by Transopedia Section** as some cards are uneven and i would also 
![improve](https://user-images.githubusercontent.com/97297724/195793437-0b2d9bf6-9ea1-40a0-91d4-3fced29ff6ae.PNG)
 like to give a little box shadow along with changing the border radius and making all the cards of same size.

**Please Assign me this issue**

Thank You

**Comment by ShrutiMishra-2002** [comment]
@theanimator20 this work is already completed
