### ISSUE TITLE
Adding a Reset button in Get in Touch Section

### ISSUE THREAD

**Issue by theanimator20** [ShrutiMishra-2002/hacktoberfest22_transopedia#43]
It would have been better if we could have add a Reset button for Get in Touch 
![121](https://user-images.githubusercontent.com/97297724/195976523-746e5aac-d7df-429e-a8a1-79b668e66484.PNG)
form in order to improve the user experience.So if a user makes a error while filling the details at a couple of places they could directly reset the form without much trouble.

i would like to work on this issue.

**Comment by ShrutiMishra-2002** [comment]
@theanimator20 goahead
