### ISSUE TITLE
Make Donation Page Responsive

### ISSUE THREAD

**Issue by mdnazisharman2803** [ShrutiMishra-2002/hacktoberfest22_transopedia#5]
- Visit the link to check the details of the page to be worked on https://shrutimishra-2002.github.io/Transopedia-website/storeanddonate/donation.html

**Comment by DugarRishab** [comment]
Hey, @mdnazisharman2803 as I am working on #7 I would also like to work o this issue. I believe that both issues can be solved together.

**Comment by aksha123-git** [comment]
I would to contribute on this issue @mdnazisharman2803

**Comment by jyotika6221** [comment]
If the issue isnt solved yet, please assign it to me.

**Comment by ShrutiMishra-2002** [comment]
@jyotika6221 done goahead

**Comment by jyotika6221** [comment]
You closed the repo, what do i do now?
