### ISSUE TITLE
Improve the UI of Store Page

### ISSUE THREAD

**Issue by mdnazisharman2803** [ShrutiMishra-2002/hacktoberfest22_transopedia#6]
- Visit the link to check the details of the page to be worked on : https://shrutimishra-2002.github.io/Transopedia-website/storeanddonate/STORE.html

**Comment by PurviSaini** [comment]
I would like to work on this issue. May I know if any specific design is to be implemented?

**Comment by DugarRishab** [comment]
Hey, @mdnazisharman2803 I would like to contribute to this issue. My experience working in an e-commerce startup makes me the perfect fit for this.

**Comment by DugarRishab** [comment]
This issue and issue #4 are similar and can be done together and I would like to contribute to both of them.

**Comment by mdnazisharman2803** [comment]
> I would like to work on this issue. May I know if any specific design is to be implemented?

You can work on it

**Comment by mdnazisharman2803** [comment]
> Hey, @mdnazisharman2803 I would like to contribute to this issue. My experience working in an e-commerce startup makes me the perfect fit for this.

You can work on th other issue assigned to you.. First come first serve.

**Comment by PurviSaini** [comment]
> > I would like to work on this issue. May I know if any specific design is to be implemented?
> 
> You can work on it

Thanks for assigning the issue!!
I am on it.

**Comment by mdnazisharman2803** [comment]
> This issue and issue #4 are similar and can be done together and I would like to contribute to both of them.

@DugarRishab  since this is beginner /intermediate level of repository. So issue is made accordingly. Please do one issue at a time, so other contributors too gets a fair chance
