### ISSUE TITLE
Improve the UI of Donation Page

### ISSUE THREAD

**Issue by mdnazisharman2803** [ShrutiMishra-2002/hacktoberfest22_transopedia#7]
- visit the link to check the details of the page to be worked on : https://shrutimishra-2002.github.io/Transopedia-website/storeanddonate/donation.html

**Comment by DugarRishab** [comment]
Hey, @mdnazisharman2803 I checked out the link. I want to contribute to this issue.
Also, Please share any specific ideas you want to be implemented.

**Comment by DugarRishab** [comment]
@mdnazisharman2803 I added A PR. Can you please review it. Also please add the label `hacktoberfest` to the repo. In the Hacktoberfest website, it shows that this repo is not participating in Hacktoberfest.

**Comment by DugarRishab** [comment]
> @DugarRishab can you check now and tell?

It still shows that this repo is not participating. 
1. Add `hacktoberfest` as a label/tag to this repo
2. Add `hacktoberfest-accepted` as a label to all merged PRs

**Comment by mdnazisharman2803** [comment]
> > @DugarRishab can you check now and tell?
> 
> It still shows that this repo is not participating.
> 
> 1. Add `hacktoberfest` as a label/tag to this repo
> 2. Add `hacktoberfest-accepted` as a label to all merged PRs

I have already done it.. I have received message

**Comment by DugarRishab** [comment]
![image](https://user-images.githubusercontent.com/83137670/193420038-a185f9de-46c2-477d-92ff-cbf365048b31.png)

This is a ss of the page. Maybe it needs time to refresh. But I cannot see the `Hacktoberfest` tag in you repo.

**Comment by mdnazisharman2803** [comment]
> ![image](https://user-images.githubusercontent.com/83137670/193420038-a185f9de-46c2-477d-92ff-cbf365048b31.png)
> 
> This is a ss of the page. Maybe it needs time to refresh. But I cannot see the `Hacktoberfest` tag in you repo.

Yeah it'll take time.. Hopefully update

**Comment by DugarRishab** [comment]
> > ![image](https://user-images.githubusercontent.com/83137670/193420038-a185f9de-46c2-477d-92ff-cbf365048b31.png)
> > This is a ss of the page. Maybe it needs time to refresh. But I cannot see the `Hacktoberfest` tag in you repo.
> 
> Yeah it'll take time.. Hopefully update

I rechecked and now it works. This repo is participating in Hacktoberfest.
